version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - govet
    - unused
  # TODO: Re-enable after fixing issues
  # - errcheck  # Fix Close() error handling
  # - staticcheck  # Configure to disable QF checks
