version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: eisenhower
    main: ./cmd/eisenhower
    binary: eisenhower
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    builds:
      - eisenhower
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

brews:
  - name: todo-eisenhower
    repository:
      owner: quii
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: "https://github.com/quii/todo-eisenhower"
    description: "Visualize todo.txt files as an Eisenhower matrix in your terminal"
    license: "MIT"
    directory: Formula
    install: |
      bin.install "eisenhower"
    test: |
      system "#{bin}/eisenhower", "--version"
